### ISSUE TITLE
Sessão sobre nós

### ISSUE THREAD

**Issue by woliveiras** [ABCMakerspace/abcmakerspace.github.io#1]
Pessoal, está faltando uma sessão "sobre nós" no site.

Eu conheci a iniciativa por indicação de um amigo e achei muito boa, porém não achava informação de jeito nenhum no site! kkkk

**Comment by crgimenes** [comment]
Você esta coberto de razão, o motivo é que usamos 99% do tempo a pagina do facebook em https://www.facebook.com/Abcmakerspace/ e não coloquei os dados aqui por puro esquecimento.
Vou concertar isso!

**Comment by woliveiras** [comment]
Show de bola!

Eu curti a página também. :smile:
